name-template: 'v$RESOLVED_VERSION-rc'
tag-template: 'v$RESOLVED_VERSION-rc'
template: |
  # What's Changed
  
  $CHANGES
categories:
  - title: 'Features'
    labels: 
      - 'feature'
      - 'task'
      - 'user stories'
      - 'business flow'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    labels: 
      - 'chore'
      - 'spike'
  - title: 'Dependency Updates'
    label: 'dependencies'

exclude-labels:
  - 'skip-changelog'