name: Go Lint

on: [push]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test lint
      run: |
          go get golang.org/x/lint/golint
          golint -set_exit_status ./...


