name: Pull Request - Go Lint and Test

on: [pull_request]

jobs:
  lint:
    name: Go Linting
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint code base
      run: |
          go get golang.org/x/lint/golint
          golint -set_exit_status ./...

  test:
    name: Go Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Running Unit Test
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
        go test ./... -cover -vet -all -short -covermode=count -coverprofile=cover.out

    - name: Generate code coverage    
      run: |
        go tool cover -func cover.out

