name: Pull Request - Go Lint and Unit test

on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint code base
      run: |
          go get golang.org/x/lint/golint
          golint -set_exit_status ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Unit Test
      env:
        AAA_SERVER_LOG_LEVEL: TRACE
        AAA_SETUP_ADMIN_ENABLE: true
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
        go test ./... -cover -vet -all -short -covermode=count -coverprofile=cover.out
        go tool cover -func cover.out

