name: Zephyr One - Release Candidate

on: [pull_request]
  # push:
  #   tags:
  #     - 'v*-rc'

jobs:
  build-release:
    name: Build Release Candidate
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone to Asia/Jakarta
      run: |
        sudo timedatectl set-timezone Asia/Jakarta  
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release Cadidate
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: | 

        draft: false
        prerelease: true
  
  deploy-app:   
    needs: build-release
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
    - name: Build GO App
      run: |
        make build-linux
        ls  
    - name: Deploy app into server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "build/zephry-one-linux.app"
        target: "/home/rasatmaj/zephryone.rasatmaja.com/test"      