name: Zephyr One - Release Candidate

on: [pull_request]

jobs:
  build-release:
    name: Build Release Candidate
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone to Asia/Jakarta
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release Cadidate
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}-${{ github.sha }}
        body: | 
          Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false  