name: Zephyr One - Release Candidate

on: [pull_request]
  # push:
  #   tags:
  #     - 'v*-rc'

jobs:
  build-release:
    name: Build Release Candidate
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone to Asia/Jakarta
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check short SHA
      run: echo ${{ steps.vars.outputs.sha_short }}  
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release Cadidate
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}.${{ steps.vars.outputs.sha_short }} 
        release_name: ${{ github.ref }}.${{ steps.vars.outputs.sha_short }} 
        body: | 

        draft: false
        prerelease: true  