name: Zephyr One - Release Candidate

on: [pull_request]
  # push:
  #   tags:
  #     - 'v*-rc'

jobs:
  # build-release:
  #   name: Build Release Candidate
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Setup timezone to Asia/Jakarta
  #     run: |
  #       sudo timedatectl set-timezone Asia/Jakarta  
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Create Release Cadidate
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: ${{ github.ref }}
  #       body: | 

  #       draft: false
  #       prerelease: true
  
  deploy-app:   
    # needs: build-release
    name: Deploy App
    runs-on: ubuntu-latest
    env:
      APP_NAME: zephyr-one
      APP_MAIN_PATH: cmd/main/main.go
    steps:
    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Building Go Apps
      run: |
          go build -a -ldflags '-extldflags "-static"' -o ${{ env.APP_NAME }}.app ${{ env.APP_MAIN_PATH }} 
    - name: Deploy app into server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "${{ env.APP_NAME }}.app, Makefile, cmd/pm2/${{ env.APP_NAME }}.json"
        target: "/home/rasatmaj/zephryone.rasatmaja.com/"
        strip_components: 1
    - name: Execute app into server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: make deploy-domainesia 