name: Go Test

on: [push]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test project
      env:
        AAA_SERVER_LOG_LEVEL: TRACE
        AAA_SETUP_ADMIN_ENABLE: true
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
        go test ./... -cover -vet -all -short -covermode=count -coverprofile=coverage.out

